resources:
- repo: self

pool:
  vmImage: Hosted Ubuntu 1604
steps:
- task: DockerCompose@0
  displayName: build
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: Azure
    dockerComposeFile: 'docker-compose.yml'
    action: 'Build services'
    additionalImageTags: '$(Build.BuildNumber)'

- task: DockerCompose@0
  displayName: push
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: Azure
    dockerComposeFile: 'docker-compose.yml'
    action: 'Push services'
    additionalImageTags: '$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: deployment'
  inputs:
    PathtoPublish: deployment
    ArtifactName: deployment


